CREATE TABLE public.contact_submissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name text NULL,
  email text NULL,
  subject text NULL,
  message text NULL,
  created_at timestamp with time zone NULL DEFAULT now(),
  CONSTRAINT contact_submissions_pkey PRIMARY KEY (id)
);
